"""init schema

Revision ID: 64bcf84d6951
Revises: 
Create Date: 2026-08-18 06:33:02.481744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64bcf84d6951'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backfill_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rows_fetched', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_year')
    )
    op.create_table('collection_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('rows_fetched', sa.Integer(), nullable=False),
    sa.Column('rows_upserted', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_self', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('delivery_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dcisn_dt', sa.Date(), nullable=True),
    sa.Column('corp_nm', sa.String(), nullable=False),
    sa.Column('corp_biz_no', sa.String(), nullable=True),
    sa.Column('contract_no', sa.String(), nullable=True),
    sa.Column('dlvr_req_no', sa.String(), nullable=False),
    sa.Column('dlvr_req_chg_cha', sa.Integer(), nullable=False),
    sa.Column('prdct_clsfc_nm', sa.String(), nullable=True),
    sa.Column('dtl_prdct_nm', sa.String(), nullable=True),
    sa.Column('dmnd_instt_nm', sa.String(), nullable=True),
    sa.Column('dlvr_amt', sa.Numeric(), nullable=True),
    sa.Column('dlvr_qty', sa.Numeric(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dlvr_req_no', 'dlvr_req_chg_cha', 'prdct_clsfc_nm', 'dtl_prdct_nm', name='uq_delivery_request_identity')
    )
    op.create_index('ix_delivery_requests_corp_nm', 'delivery_requests', ['corp_nm'], unique=False)
    op.create_index('ix_delivery_requests_dcisn_dt', 'delivery_requests', ['dcisn_dt'], unique=False)
    op.create_index('ix_delivery_requests_dmnd_instt_nm', 'delivery_requests', ['dmnd_instt_nm'], unique=False)
    op.create_index('ix_delivery_requests_dtl_prdct_nm', 'delivery_requests', ['dtl_prdct_nm'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_delivery_requests_dtl_prdct_nm', table_name='delivery_requests')
    op.drop_index('ix_delivery_requests_dmnd_instt_nm', table_name='delivery_requests')
    op.drop_index('ix_delivery_requests_dcisn_dt', table_name='delivery_requests')
    op.drop_index('ix_delivery_requests_corp_nm', table_name='delivery_requests')
    op.drop_table('delivery_requests')
    op.drop_table('competitors')
    op.drop_table('collection_runs')
    op.drop_table('backfill_progress')
    # ### end Alembic commands ###
